import mobileNav from './modules/mobile-nav.js';
import { swiper } from './modules/swiper.js';
import { headerAnimation } from './modules/animations/header.js';
import { homeAnimation } from './modules/animations/home.js';
import { aboutAnimation } from './modules/animations/about.js';
import { workingAnimation } from './modules/animations/working.js';
import { workAnimation } from './modules/animations/work.js';
import { visionAnimation } from './modules/animations/vision.js';
import { howAnimation } from './modules/animations/how.js';
import { impactAnimation } from './modules/animations/impact.js';
import { storyAnimation } from './modules/animations/story.js';
import { contactAnimation } from './modules/animations/contact.js';
import { footerAnimation } from './modules/animations/footer.js';
import { initTheme } from './modules/theme.js';
mobileNav();
initTheme();